services:
  - type: web
    name: sticker-address-printer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT 'sticker_printer.web:create_app()'
